## Data in the Wild - Annotation Exercises - Part 2 Airways

In these exercises you will use some existing crowdsourced data, to practice working with inter-observer agreement.

This dataset contains crowdsourced segmentations measurements of airways in slices of chest CT images. An airway appears like a dark circle or ellipse, with a lighter ring around it. You can see examples of airways and read more about the study [in this paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0249580).

Each annotation *task* is an image, which contains an airway. The annotator has to draw two ellipses: one inside the airway, and one outside the airway. The combination of a specific task and a specific annotator is a *result*, which contains two ellipses.

The original crowdsourced data was stored as ellipse coordinates drawn by the annotators, you can find the images and the raw data here: https://github.com/adriapr/crowdairway

For this exercise, this data has already been cleaned (removing some invalid annotations) and processed to measure how large the ellipses are. The CSV therefore contains:

* task_id - ID of the image
* annotator_id - anonymized ID of the annotator
* result_id - ID of this task/annotator combination
* outer - the area of the outer ellipse
* inner - the area of the inner ellipse

There is also a CSV with expert annotations for these airways with:
* task_id - ID of the image
* subject_id - which patient has this airway
* airway_id - index of the airway in that patient
* generation - the generation of the airway, higher generation airways are smaller
* outer1, outer2 - outer ellipse annotated by experts 1 and 2
* inner1, inner2 - inner ellipse annotated by experts 1 and 2

In [1]:
#Import the needed libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Question 1: Explore the data
The objective here is to understand the content of the data:
* airway_annotations.csv has the crowdsourced results for the tasks (1 task = 1 airway image)
* airway_annotations_experts.csv has the ground truth results from the two experts

**Task: Load the dataframe from the data/airways folder and display a few rows from each of better understand their content and how they are connected**

In [2]:
##Your code##
df_res = pd.read_csv("airway_annotations.csv")
df_truth  = pd.read_csv("airway_annotations_experts.csv")

**Task**: Investigate how many results each airway has, and how many results overall were made by each annotator.

**Question**: Are the statistics above what you would expect from a crowdsourcing task? Is this similar or different than the skin lesion annotations?

## Question 2: Combining results per task

We now have a case where not all annotators annotated all images.

If we are interested how the crowd did overall, we want to combine their results into a single measurement per task, and compare it to the experts.

The following code combines the measurements for each task using the *mean* function.

In [3]:

task_list = []

for task_id in df_res['task_id'].unique():
    task_results = df_res.loc[df_res['task_id'] == task_id]

    outer_mean = task_results['outer'].mean()
    inner_mean = task_results['inner'].mean()

    task_dict = {
                'task_id':      task_id,
                'num_combined': len(task_results),
                'outer_mean': outer_mean,
                'inner_mean': inner_mean,
                }
    task_list.append(task_dict)

df_task_combined = pd.DataFrame(task_list)
df_task_combined.head(5)

   task_id  num_combined  outer_mean  inner_mean
0      275            20   35.590309   12.601725
1      778            20   18.389231    6.241597
2     1420            20   16.436107    5.355605
3       13            20    9.707073    2.518653
4     2246            20   31.733718   15.531632

**Question:** Can you think of a situation where the mean would not be a suitable way of combining? What could be an alternative?

**Task:** Try out other ways of combining and look at the differences - does this match your intuition?

_Your comments_

## Question 3: Comparing results to experts
Now we can compare the combined crowd results to the two experts, and compare the experts to each other.

For the following exercises, you can consider the experts and the (combined) crowd, as three different annotators.

In [4]:
df_truth.head(5)

,Unnamed: 0,task_id,subject_id,airway_id,generation,inner1,outer1,inner2,outer2
0,0,275,4,76,6,9.1317,27.191,7.73560,25.3050
1,1,778,8,104,8,3.4867,18.623,2.56540,13.4980
2,2,1354,18,43,6,4.8300,17.848,5.16100,16.4510
3,3,426,5,56,7,2.8406,14.951,0.93857,9.0357
4,4,1420,18,116,6,4.7073,15.617,2.90990,11.9350

**Task: Create simple scatterplots of each pair of annotators (expert1, expert2, combined crowd). Calculate the correlation of the measurements, and add it to the title of each plot.**

In [5]:
##Your code##

**Question:** How does the crowd compare to the experts - are there particular biases you can notice? Are there differences for the outer vs inner measurements?

_Your comments_

**Task:** Repeat the analysis by looking at the airways of one subject at a time. Is the crowd better at some subjects than others?

In [6]:
## Your code

**Task**: Now look at the generation of the airways. The generation defines how far from the trachea (wind pipe) the airway is, higher generations are typically smaller.

What do you observe?

In [7]:
## Your code

## Bland-Altman

If you have continuous data, to investigate if different annotators are systmatically biased you can use a Bland-Altman plot.

This is simply plotting the absolute *difference* of the annotators against their *mean*. In our case, this can for example tell you if the annotators disagree more on smaller or larger values.

**Task:** Write or find a function to create a Bland-Altman plot.

In [8]:
##Your code##

**Question**: Does the plot show you some patterns that you could not see with the simple scatterplot? Do your observations match with the per-generation analysis?

_Your comments_